version: '2'
services:
    rbaccounts-app:
        image: rbaccounts
        external_links:
            - rbaccounts-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rbaccounts?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rbaccounts-mysql:
        extends:
            file: mysql.yml
            service: rbaccounts-mysql
